# Generated by Django 4.0.6 on 2023-01-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketname', models.CharField(max_length=30)),
                ('dates', models.CharField(max_length=30)),
                ('mclassname', models.CharField(max_length=30)),
                ('avgprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predict_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
