# Generated by Django 4.1.5 on 2023-01-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DELNG_DE', models.CharField(max_length=30)),
                ('MRKT_NM', models.CharField(max_length=30)),
                ('CPR_NM', models.CharField(max_length=30)),
                ('PRDLST_NM', models.CharField(max_length=30)),
                ('SPCIES_NM', models.CharField(max_length=30)),
                ('GRAD', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('PRI_MAX', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRI_MIN', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRI_AVE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRI_PRED', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
